### ISSUE TITLE
It looks like the image is no longer available

### ISSUE THREAD

**Issue by alex-w-k** [img2tab/okiomov#10]
http://swcdn.apple.com/content/downloads/35/53/091-93471/ff5kp0aiow1d87t494xp5twbugymnlvz16/BaseSystem.dmg no longer seems to point to anything.

**Comment by alex-w-k** [comment]
It looks like the new URL is: http://swcdn.apple.com/content/downloads/01/22/041-19985/q7s69dmdnh5jhfrmy1jp80m8vy2eh0dst2/BaseSystem.dmg

**Comment by sej7278** [comment]
full fix is in issue #11
