### ISSUE TITLE
Could not validate soure - invalid argument

### ISSUE THREAD

**Issue by codewolf813** [img2tab/okiomov#11]
![image](https://user-images.githubusercontent.com/22500241/50314823-634ea680-047e-11e9-9af0-483f7d2a643d.png)
I get this error when I get to this point. Any advise on how to proceed?

**Comment by codewolf813** [comment]
![image](https://user-images.githubusercontent.com/22500241/50315567-49fb2980-0481-11e9-9179-9e0f174c2652.png)

**Comment by Mycologist** [comment]
In addition to updating the path on line 110 to be http://swcdn.apple.com/content/downloads/01/22/041-19985/q7s69dmdnh5jhfrmy1jp80m8vy2eh0dst2/BaseSystem.dmg
 you also need to update line 373 to have http://swcdn.apple.com/content/downloads/01/22/041-19985/q7s69dmdnh5jhfrmy1jp80m8vy2eh0dst2/ as the path

Unfortunately I never got the license popup that's listed later in the script and I couldn't get the installer to load manually either.

**Comment by vgruiz** [comment]
After making the changes Mycologist posted, I'm still getting the same error as OP. Any suggestions?

**Comment by img2tab** [comment]
Updated Apple store URLs accordingly.

**Comment by wilber82** [comment]
Still same issue
