### ISSUE TITLE
A different error loading base system onto disk

### ISSUE THREAD

**Issue by dekaufman** [img2tab/okiomov#7]
I had an interruption while running the script, so I'm trying to pick up where I left off.  So I commented everything above the point of interruption (except environment variable definitions), letting the modified script begin at the command `asr restore --source /Volumes/Mojave/BaseSystem.dmg -- target /Volumes/Install --erase --noprompt`.

It gives an error response:
```
"/Volumes/Install" is not a volume
Could not validate target - No such file or directory
```
For what it's worth, `ls \Volumes` returns
```
Mojave        OS X Base System        OS X Base System 1
```

Any suggestions?  Thanks.

**Comment by ISTEricBrown** [comment]
Did you end up finding a solution? I still have this error

**Comment by dekaufman** [comment]
No, I had to start from scratch.

**Comment by img2tab** [comment]
There is a bug in the keycode mechanism that causes keystrokes to be missed, which results in the failure to create this volume. Will investigate.
